// ASCII messages based
// on CueServer's protocol.
const CueServerLookup = {

  PRE_SHOW: 'CUE 1 Go',
  SHOW_START: 'CUE 2 Go',
  HIGHLIGHT_EASEL: 'CUE 3 Go',
  HIGHLIGHT_CAGES: 'CUE 4 Go',
  HIGHLIGHT_POPPER: 'CUE 5 Go',
  HIGHLIGHT_CHUTE: 'CUE 6 Go',
  HIGHLIGHT_POSTER: 'CUE 789 Go',
  VISTAS_ENTER_POPPER: 'CUE 7 Go',
  VISTA_TRAIN_ENTER: 'CUE 8 Go',
  VISTAS_EXIT_POPPER: 'CUE 9 Go',
  VISTA_TRAIN_EXIT: 'CUE 20 Go',
  VISTA_TRAIN_EXIT_OFF: 'CUE 21 Go',
  UNPLUG_BLACKOUT: 'CUE 10 Go',
  PLUG_IN_LOCKDOWN: 'CUE 11 Go',
  LOCKDOWN_RELEASE: 'CUE 13 Go',
  POST_SHOW: 'CUE 18 Go',

  BADGE_V: 'CUE 22 Go',
  BADGE_I: 'CUE 23 Go',
  BADGE_S: 'CUE 24 Go',
  BADGE_T: 'CUE 25 Go',
  BADGE_A: 'CUE 26 Go',

  GAME_2_PRESHOW: 'CUE 94 Go', 

  GAME_2_BADGE_V: 'CUE 95 Go',
  GAME_2_BADGE_I: 'CUE 96 Go',
  GAME_2_BADGE_S: 'CUE 97 Go',
  GAME_2_BADGE_T: 'CUE 98 Go',
  GAME_2_BADGE_A: 'CUE 99 Go',

  HIGHLIGHT_VARIATION_CIRCUIT: 'CUE 100 Go',
  HIGHLIGHT_INHERITANCE_CIRCUIT: 'CUE 101 Go',
  HIGHLIGHT_SELECTION_CIRCUIT: 'CUE 102 Go',
  HIGHLIGHT_TIME_CIRCUIT: 'CUE 103 Go',
  HIGHLIGHT_ADAPTATION_CIRCUIT: 'CUE 104 Go',
  FIREWORKS_FINALE: 'CUE 105 Go',
  VISTA_DROP: 'CUE 106 Go',
  GAME_2_POST_SHOW: 'CUE 107 Go', 

};

export default CueServerLookup;
